name: Create executables

on:
  push:
    branches:
    - master

permissions:
  contents: write

jobs:
  build-windows-exe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: main-repo
        
    - name: setup mingw
      run: sudo apt-get update && sudo apt-get install g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64 gcc-mingw-w64-i686
        
    - name: build windows exe
      run: bash ./main-repo/build.sh

    - name: Generate release tag and name
      id: release_meta
      run: |
        VERSION=$(date +"%Y.%m.%d-%H%M%S")
        echo "tag=$VERSION" >> "$GITHUB_OUTPUT"
        echo "name=Automated Build $VERSION" >> "$GITHUB_OUTPUT"
      
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release_meta.outputs.tag }}
        release_name: Release ${{ steps.release_meta.outputs.name }}
        draft: false
        prerelease: false

    - name: Zip build output
      run: zip -j handmade-windows.zip ./main-repo/build/handmade-windows*

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: handmade-windows.zip
        asset_name: handmade-windows.zip
        asset_content_type: application/octet-stream
        
