name: Create executables

on:
  push:
    branches:
    - master

permissions:
  contents: write

jobs:
  build-windows-exe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: main-repo
        
    - name: setup mingw
      run: sudo apt-get update && sudo apt-get install g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 g++-mingw-w64-i686
        
    - name: build windows exe
      run: bash ./main-repo/build.sh

    - name: Generate release tag and name
      id: release_meta
      run: |
        VERSION=$(date +"%Y.%m.%d")-$(git rev-parse --short HEAD)
        echo "tag=$VERSION" >> "$GITHUB_OUTPUT"
        echo "name=Automated Build $VERSION" >> "$GITHUB_OUTPUT"

    - name: Zip build output
      run: zip -j handmade-windows.zip ./main-repo/build/handmade-windows*
      
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release_meta.outputs.tag }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: handmade-windows.zip
