name: Create executables

on:
  push:
    branches:
    - master

jobs:
  build-windows-exe:
    runs-on: ubuntu-latest

    steps:
    - name: test
      run: |
        ls
    - name: setup mingw
      run: |
        sudo apt-get install gcc-mingw-w64
    - name: build windows exe
      run: |
        sh ./build.sh
      
